(provide 'utils)

(defun divisor-in-list (i testlist)
  (dolist (n testlist)
    (if (= 0 (mod i n))
        (return-from divisor-in-list t)
        )
    )
  (return-from divisor-in-list nil)
  )

(defun primes-leq (upbound)
  (if (< upbound 2)
      (return-from primes-leq nil))
  (let* ((prime-list (list 2)) (i 3))
    (loop while (<= i upbound) do
      (when (not (divisor-in-list i prime-list))
          (nconc prime-list (list i)))
      (setq i (+ i 2)))
    (return-from primes-leq prime-list)
    )
  )
